module.exports = {
    host: '',
    host_channel: '',
    insesh: false,
    all_roles: ["werewolf","minion","seer","robber","troublemaker","drunk","insomniac","tanner","villager","mason"],
    action_roles: ["werewolf","seer","robber","troublemaker","drunk"],
    swap_order: ["robber","troublemaker","drunk"],
    swaps: [],
    players: [],
    roles: [],
    assigns: new Map(),
    middle: [],
    votes: [],
    time: 40,
    time_elapsed: 0,
    alert_times: [180,120,60,30,10,3,2,1],
    emoji_letters: ['🇦','🇧','🇨','🇩','🇪','🇫','🇬','🇭','🇮','🇯','🇰','🇱','🇲','🇳','🇴','🇵','🇶','🇷','🇸','🇹','🇺','🇻','🇼','🇽','🇾','🇿'],
    emoji_middle: ['⬅️','⬆️','➡️'],
};